NUMPY

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
import numpy as np

arr = np.array([23,45,67,78,45,23])

print(arr)

[23 45 67 78 45 23]


1-d array

In [2]:
import numpy as np

arr = np.array([23,45,67,78,45,23])

print(arr)

[23 45 67 78 45 23]


2-d array

In [3]:
import numpy as np

arr = np.array([[23,45,67], [78, 45, 23]])

print(arr)

[[23 45 67]
 [78 45 23]]


3-d array

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Multiplication

In [5]:
import numpy as np

a = np.array([5, 7, 3, 1])
b = np.array([90, 50, 0, 30])

c = a * b
print(c)


[450 350   0  30]


Addition

In [6]:
import numpy as np

d = np.array([5, 7, 3, 1])
e = np.array([90, 50, 0, 30])

f = d + e
print(f)

[95 57  3 31]


Subtraction

In [7]:
import numpy as np

g = np.array([5, 7, 3, 1])
h = np.array([90, 50, 0, 30])

i = g - h
print(i)

[450 350   0  30]


Division

In [9]:
import numpy as np

j = np.array([5, 7, 3, 1])
k = np.array([90, 50, 0, 30])

l = k / j
print(l)

[18.          7.14285714  0.         30.        ]
